version: '2'

services:
  postgresql:
    image: sameersbn/postgresql:9.4-22
    container_name: redmine_db
    environment:
      - DB_USER=redmine
      - DB_PASS=password
      - DB_NAME=redmine_production
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /srv/docker/redmine/postgresql:/var/lib/postgresql

  redmine:
    image: sameersbn/redmine:3.3.0
    links:
      - postgresql:postgresql
    container_name: redmine
    depends_on:
      - postgresql
    ports:
      - "10083:80"
    environment:
      - REDMINE_PORT=10083

      - SMTP_ENABLED=true
      - SMTP_PORT=25
      - SMTP_HOST=mail1.astri.org
      - SMTP_STARTTLS=false

      - DB_ADAPTER=postgresql
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USER=redmine
      - DB_PASS=password
      - DB_NAME=redmine_production
    volumes:
      - /srv/docker/redmine/redmine:/home/redmine/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
