version: '2'

services:
  redis:
    restart: always
    image: sameersbn/redis:latest
    container_name: gitlabs_redis
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /srv/docker/gitlabs/redis:/var/lib/redis

  postgresql:
    restart: always
    image: sameersbn/postgresql:9.4-22
    container_name: gitlabs_db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /srv/docker/gitlabs/postgresql:/var/lib/postgresql
    environment:
      - DB_NAME=gitlabhq_production
      - DB_USER=gitlab
      - DB_PASS=password
      - DB_EXTENSION=pg_trgm

  gitlabs:
    restart: always
    image: sameersbn/gitlab:8.9.1
    container_name: gitlabs
    links:
      - redis:redisio
      - postgresql:postgresql
    depends_on:
      - redis
      - postgresql
    ports:
      - "10080:80"
      - "10022:22"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /srv/docker/gitlabs/gitlab:/home/git/data
    environment:
      - GITLAB_HOST=${HOST_IP}
      - GITLAB_PORT=10080
      - GITLAB_ROOT_PASSWORD=mypassword
      - GITLAB_SSH_PORT=10022
      - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alpha-numeric-string
      - SMTP_ENABLED=true
      - SMTP_PORT=25
      - SMTP_HOST=mail1.astri.org
      - SMTP_STARTTLS=false
      
      - DB_ADAPTER=postgresql
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USER=gitlab
      - DB_PASS=password
      - DB_NAME=gitlabhq_production

      - REDIS_HOST=redis
      - REDIS_PORT=6379

  gitlabsRunner:
    image: gitlab/gitlab-runner:1.3.3
    container_name: gitlab-runner
    volumes:
      - /srv/docker/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
